services:
  postgres_auth:
    image: postgres:13
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin_data:/var/lib/postgresql/data
    ports:
      - '5050:80'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_auth
    restart: always
    environment:
      PORT: 3000
      NODE_ENVIRONMENT: dev
      DB_HOST: postgres_auth
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: auth
      DB_TYPE: postgres
      DB_PORT: 5432
      HASH_SALT: 10
    expose:
      - "3000"